### ISSUE TITLE
Showing the tags for deleted features in changest map

### ISSUE THREAD

**Issue by jothirnadh** [osmlab/changeset-map#46] opened 2016-05-25 13:09 UTC
The changeset map in OSM changeset analyzer is just showing the tags of the features that are modified, but the changeset map is not showing the tags of the features that are deleted. It would be great if we can fetch the tags of deleted features in changeset map to make the verification process much easier.

Changeset example - http://osmcha-django-staging.tilestream.net/39091810/

**Comment by planemad** [comment] 2016-05-26 14:14
duplicate of #7

**Comment by batpad** [comment] 2016-05-27 07:36
Closing here since it is a duplicate of #7

**Closed by batpad** 2016-05-27 07:36 UTC
