### ISSUE TITLE
Better handling of relations in the changeset map

### ISSUE THREAD

**Issue by nikhilprabhakar** [osmlab/changeset-map#120] opened 2017-03-23 09:16 UTC
While I was reviewing Paris in OSMCha, I came across this changeset where there are multiple squares in the changeset map. Per voice w/ @ajithranka and @rasagy, the squares get shown on the map when there is a change made to relations in OSM. But changeset like the below mentioned where there are changes to multiple relations, the changeset map gets really crowded and it becomes difficult to review the changeset. Can we handle/show relation's changes in a better way to avoid this? Maybe a button to enable and disable or taking this out entirely and replacing it with something else? This would fasten the review for this kind of changesets and makes it less complex.

**OSMCha changeset link in question:** https://osmcha.mapbox.com/47072405/

#### Screenshots:

![screen shot 2017-03-23 at 2 42 04 pm](https://cloud.githubusercontent.com/assets/11845908/24240277/f6b63b66-0fd6-11e7-82fb-08aa2aebc1f8.png)
![screen shot 2017-03-23 at 2 42 09 pm](https://cloud.githubusercontent.com/assets/11845908/24240278/f6b74984-0fd6-11e7-8693-7d5a988678b6.png)
![screen shot 2017-03-23 at 2 42 17 pm](https://cloud.githubusercontent.com/assets/11845908/24240280/f6c41862-0fd6-11e7-941f-77b1cf70fb6a.png)

cc:// @planemad @chtnha @manoharuss @geohacker @krishnanammala

**Comment by batpad** [comment] 2017-03-23 10:00
Duplicate of #108 - let's keep discussions of how a better handling of relations should work there. Closing here.

**Closed by batpad** 2017-03-23 10:00 UTC
